export interface IndigoFormState {
  // ── Run Details ──────────────────────────────────────────────────
  tgl: string;
  start: string;
  stop: string;
  // ── Process Parameters ────────────────────────────────────────────
  mc: string;
  speed: string;
  bak_celup: string;
  bb: string;
  p: string;
  te: string;
  ne: string;
  // ── Dye Bath Indigo ───────────────────────────────────────────────
  bak_count: string;
  indigo_conc: string;
  indigo_bak: string;
  // ── Dye Bath Sulfur ───────────────────────────────────────────────
  has_sulfur: boolean;
  sulfur_conc: string;
  sulfur_bak: string;
  // ── Output ────────────────────────────────────────────────────────
  total_meters: string;
  keterangan: string;
  // ── Quality Parameters (lab results) ─────────────────────────────
  mc_idg: string;
  strength_val: string;
  strength: string;
  elongasi: string;
  elongasi_idg: string;
  cv_pct: string;
  tenacity: string;
  // ── Machine Parameters ────────────────────────────────────────────
  konst_idg: string;
  konst_sulfur: string;
  visc: string;
  ref: string;
  size_box: string;
  scoring: string;
  jetsize: string;
  moisture_mahlo: string;
  temp_dryer: string;
  temp_mid_dryer: string;
  temp_size_box_1: string;
  temp_size_box_2: string;
  size_box_1: string;
  size_box_2: string;
  squeezing_roll_1: string;
  squeezing_roll_2: string;
  immersion_roll: string;
  dryer: string;
  take_off: string;
  winding: string;
  press_beam: string;
  hardness: string;
  hydrolic_pump_1: string;
  hydrolic_pump_2: string;
  unwinder: string;
  dyeing_tens_wash: string;
  dyeing_tens_warna: string;
  // ── Chemical Usage — Sizing ───────────────────────────────────────
  polisize_hs: string;
  polisize_1_2: string;
  armosize: string;
  armosize_1_1: string;
  armosize_1_2: string;
  armosize_1_3: string;
  armosize_1_5: string;
  armosize_1_7: string;
  quqlaxe: string;
  armo_c: string;
  vit_e: string;
  armo_d: string;
  tapioca: string;
  a_308: string;
  // ── Chemical Usage — Dyeing ────────────────────────────────────────
  indigo: string;
  caustic: string;
  hydro: string;
  solopol: string;
  serawet: string;
  primasol: string;
  cottoclarin: string;
  setamol: string;
  granular: string;
  granule: string;
  grain: string;
  wet_matic: string;
  fisat: string;
  breviol: string;
  csk: string;
  comee: string;
  dirsol_rdp: string;
  primasol_nf: string;
  zolopol_phtr: string;
  cottoclarin_2: string;
  sanwet: string;
  marcerize_caustic: string;
  sanmercer: string;
  sancomplex: string;
  exsess_caustic: string;
  exsess_hydro: string;
  dextoor: string;
  ltr: string;
  diresol_black_kas: string;
  sansul_sdc: string;
  caustic_2: string;
  dextros: string;
  solopol_2: string;
  primasol_2: string;
  serawet_2: string;
  cottoclarin_3: string;
  saneutral: string;
  dextrose_adjust: string;
  optifik_rsl: string;
  ekalin_f: string;
  solopol_phtr: string;
  // ── Bak temperatures ───────────────────────────────────────────────
  bak_1: string;
  bak_2: string;
  bak_3: string;
  bak_4: string;
  bak_5: string;
  bak_6: string;
  bak_7: string;
  bak_8: string;
  bak_9: string;
  bak_10: string;
  bak_11: string;
  bak_12: string;
  bak_13: string;
  bak_14: string;
  bak_15: string;
  bak_16: string;
}

export const emptyIndigoForm = (): IndigoFormState => ({
  tgl: new Date().toISOString().split('T')[0],
  start: '',
  stop: '',
  mc: '',
  speed: '',
  bak_celup: '',
  bb: '',
  p: '',
  te: '',
  ne: '',
  bak_count: '',
  indigo_conc: '',
  indigo_bak: '',
  has_sulfur: false,
  sulfur_conc: '',
  sulfur_bak: '',
  total_meters: '',
  keterangan: '',
  mc_idg: '',
  strength_val: '',
  strength: '',
  elongasi: '',
  elongasi_idg: '',
  cv_pct: '',
  tenacity: '',
  konst_idg: '',
  konst_sulfur: '',
  visc: '',
  ref: '',
  size_box: '',
  scoring: '',
  jetsize: '',
  moisture_mahlo: '',
  temp_dryer: '',
  temp_mid_dryer: '',
  temp_size_box_1: '',
  temp_size_box_2: '',
  size_box_1: '',
  size_box_2: '',
  squeezing_roll_1: '',
  squeezing_roll_2: '',
  immersion_roll: '',
  dryer: '',
  take_off: '',
  winding: '',
  press_beam: '',
  hardness: '',
  hydrolic_pump_1: '',
  hydrolic_pump_2: '',
  unwinder: '',
  dyeing_tens_wash: '',
  dyeing_tens_warna: '',
  polisize_hs: '',
  polisize_1_2: '',
  armosize: '',
  armosize_1_1: '',
  armosize_1_2: '',
  armosize_1_3: '',
  armosize_1_5: '',
  armosize_1_7: '',
  quqlaxe: '',
  armo_c: '',
  vit_e: '',
  armo_d: '',
  tapioca: '',
  a_308: '',
  indigo: '',
  caustic: '',
  hydro: '',
  solopol: '',
  serawet: '',
  primasol: '',
  cottoclarin: '',
  setamol: '',
  granular: '',
  granule: '',
  grain: '',
  wet_matic: '',
  fisat: '',
  breviol: '',
  csk: '',
  comee: '',
  dirsol_rdp: '',
  primasol_nf: '',
  zolopol_phtr: '',
  cottoclarin_2: '',
  sanwet: '',
  marcerize_caustic: '',
  sanmercer: '',
  sancomplex: '',
  exsess_caustic: '',
  exsess_hydro: '',
  dextoor: '',
  ltr: '',
  diresol_black_kas: '',
  sansul_sdc: '',
  caustic_2: '',
  dextros: '',
  solopol_2: '',
  primasol_2: '',
  serawet_2: '',
  cottoclarin_3: '',
  saneutral: '',
  dextrose_adjust: '',
  optifik_rsl: '',
  ekalin_f: '',
  solopol_phtr: '',
  bak_1: '',
  bak_2: '',
  bak_3: '',
  bak_4: '',
  bak_5: '',
  bak_6: '',
  bak_7: '',
  bak_8: '',
  bak_9: '',
  bak_10: '',
  bak_11: '',
  bak_12: '',
  bak_13: '',
  bak_14: '',
  bak_15: '',
  bak_16: '',
});
