[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix ../.. --ignore-scripts",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build --workspace=@erp-sinaran/prisma",
  "npm run prisma:generate",
  "npx tsc"
]

[start]
cmd = "node dist/server.js"
